Add BUILDING and CONTRIBUTING docs, add more sections to templates.
touchlab/xcode-kotlin pull request #90
Opened 2022-11-28 13:27 UTC by JuliaJakubcova

2022-11-28 16:35 UTC, samhill303 requested changes

2022-11-28 16:35 UTC, samhill303 commented on CONTRIBUTING.md
> +<channel-name> channel. To join the Kotlin Community Slack, [request access here](http://slack.kotlinlang.org/).
channel-name is missing

2022-12-02 13:57 UTC, samhill303 commented on CONTRIBUTING.md
> +<channel-name> channel. To join the Kotlin Community Slack, [request access here](http://slack.kotlinlang.org/).
#touchlab-tools https://kotlinlang.slack.com/archives/CTJB58X7X

2022-12-02 14:26 UTC, psh commented on CONTRIBUTING.md
> +[this channel](https://kotlinlang.slack.com/archives/CTJB58X7X). To join the Kotlin Community Slack,
```diff
-[this channel]
+[the #touchlab-tools channel]
```

2022-12-12 20:54 UTC, samhill303 approved these changes

2022-12-13 11:00 UTC, merged